server:
  port: 9999
  servlet:
    context-path: /api
spring:
#  mysql配置
  datasource:
    username: root
#    password: root@QWE123
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matutinal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://120.55.180.212:3306/matutinal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true