server:
  port: 9999
spring:
#  mysql配置
  datasource:
    username: root
    password: root@QWE123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.55.180.212:3306/matutinal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai